package com2008.team.project;

import java.util.ArrayList;

public class AddProperty extends javax.swing.JPanel {
    
    private class Bedroom{
        private Bed bed1;
        private Bed bed2;
        private Bedroom(){
        }
        private void setBed1(String bed1){
            switch(bed1){
                case "Single bed":
                    this.bed1 = Bed.SINGLE;
                    break;
                case "Double bed":
                    this.bed1 = Bed.DOUBLE;
                    break;
                case "Kingsize bed":
                    this.bed1 = Bed.KINGSIZE;
                    break;
                case "Bunk bed":
                    this.bed1 = Bed.BUNK;
                    break;
                default:
                    this.bed1 = Bed.SINGLE;
                    break;
            }
        }
        private void setBed2(String bed2){
            switch(bed2){
                case "Single bed":
                    this.bed2 = Bed.SINGLE;
                    break;
                case "Double bed":
                    this.bed2 = Bed.DOUBLE;
                    break;
                case "Kingsize bed":
                    this.bed2 = Bed.KINGSIZE;
                    break;
                case "Bunk bed":
                    this.bed2 = Bed.BUNK;
                    break;
                default:
                    this.bed2 = null;
                    break;
            }
        }
        private String getBed1String(){
            switch(bed1){
                case SINGLE:
                    return "Single bed";
                case DOUBLE:
                    return "Double bed";
                case KINGSIZE:
                    return "Kingsize bed";
                case BUNK:
                    return "Bunk bed";
                default:
                    return "Single bed";
            }
        }
        private String getBed2String(){
            if (bed2 == null){
                return "None";
            }
            switch(bed2){
                case SINGLE:
                    return "Single bed";
                case DOUBLE:
                    return "Double bed";
                case KINGSIZE:
                    return "Kingsize bed";
                case BUNK:
                    return "Bunk bed";
                default:
                    return "None";
            }
        }
    }
    
    private class Bathroom{
        private boolean toilet;
        private boolean bath;
        private boolean shower;
        private boolean shared;
        private Bathroom(){
        }
    }

    private ArrayList<Bedroom> bedrooms = new ArrayList<>();
    private ArrayList<Bathroom> bathrooms = new ArrayList<>();
    
    private AddProperty2 addProperty2Instance;
    private Main jFrameInstance;
    private String email;
    
    private int currentBedroomPage = 1;
    private int currentBathroomPage = 1;
    
    /**
     * Creates new form AddProperty
     */
    public AddProperty(Main jFrameInstance, String email) {
        initComponents();
        this.jFrameInstance = jFrameInstance;
        this.email = email;
        addProperty2Instance = new AddProperty2(jFrameInstance, this);
        bedrooms.add(new Bedroom());
        bathrooms.add(new Bathroom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        returnButton = new javax.swing.JButton();
        addPropertyText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        propertyNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        locationTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        houseNumberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        streetNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        postcodeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        placeNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextField = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        bedroomText = new javax.swing.JLabel();
        sleepingNextButton = new javax.swing.JButton();
        sleepingPrevButton = new javax.swing.JButton();
        sleepingNewButton = new javax.swing.JButton();
        sleepingDeleteButton = new javax.swing.JButton();
        bed1Combobox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        bed2Combobox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        bedLinenCheckbox = new javax.swing.JCheckBox();
        towelsCheckbox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        bathroomText = new javax.swing.JLabel();
        bathingNextButton = new javax.swing.JButton();
        bathingPrevButton = new javax.swing.JButton();
        bathingNewButton = new javax.swing.JButton();
        bathingDeleteButton = new javax.swing.JButton();
        toiletCheckbox = new javax.swing.JCheckBox();
        showerCheckbox = new javax.swing.JCheckBox();
        bathCheckbox = new javax.swing.JCheckBox();
        sharedCheckbox = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        hairDryerCheckbox = new javax.swing.JCheckBox();
        shampooCheckbox = new javax.swing.JCheckBox();
        toiletPaperCheckbox = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        tvCheckbox = new javax.swing.JCheckBox();
        wifiCheckbox = new javax.swing.JCheckBox();
        satelliteCheckbox = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        basicProvisionsCheckbox = new javax.swing.JCheckBox();
        cookwareCheckbox = new javax.swing.JCheckBox();
        tablewareCheckbox = new javax.swing.JCheckBox();
        dishwasherCheckbox = new javax.swing.JCheckBox();
        ovenCheckbox = new javax.swing.JCheckBox();
        stoveCheckbox = new javax.swing.JCheckBox();
        microwaveCheckbox = new javax.swing.JCheckBox();
        refrigeratorCheckbox = new javax.swing.JCheckBox();
        onRoadParkingCheckbox = new javax.swing.JCheckBox();
        patioCheckbox = new javax.swing.JCheckBox();
        freeOnSiteParkingCheckbox = new javax.swing.JCheckBox();
        paidCarParkCheckbox = new javax.swing.JCheckBox();
        streamingCheckbox = new javax.swing.JCheckBox();
        dvdPlayerCheckbox = new javax.swing.JCheckBox();
        boardGamesCheckbox = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        centralHeatingCheckbox = new javax.swing.JCheckBox();
        washingMachineCheckbox = new javax.swing.JCheckBox();
        dryingMachineCheckbox = new javax.swing.JCheckBox();
        fireExtinguisherCheckbox = new javax.swing.JCheckBox();
        firstAidCheckbox = new javax.swing.JCheckBox();
        smokeAlarmCheckbox = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        bbqCheckbox = new javax.swing.JCheckBox();

        returnButton.setBackground(new java.awt.Color(194, 123, 160));
        returnButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_arrow_resized.png"))); // NOI18N
        returnButton.setText("Return");
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.setIconTextGap(8);
        returnButton.setMaximumSize(new java.awt.Dimension(168, 54));
        returnButton.setMinimumSize(new java.awt.Dimension(168, 54));
        returnButton.setPreferredSize(new java.awt.Dimension(168, 54));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        addPropertyText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        addPropertyText.setText("Add Property");

        propertyNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        propertyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyNameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Property Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertyNameTextField)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        locationTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("General Location");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(locationTextField))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        houseNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        houseNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("House No.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(houseNumberTextField)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(houseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        streetNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        streetNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Street Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(streetNameTextField))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(streetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        postcodeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        postcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postcodeTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Postcode");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postcodeTextField))
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        placeNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeNameTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Place Name e.g. London");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(placeNameTextField)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextButton.setText("Next");
        nextButton.setMaximumSize(new java.awt.Dimension(168, 54));
        nextButton.setMinimumSize(new java.awt.Dimension(168, 54));
        nextButton.setPreferredSize(new java.awt.Dimension(168, 54));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Description");

        descriptionTextField.setColumns(20);
        descriptionTextField.setLineWrap(true);
        descriptionTextField.setRows(5);
        jScrollPane1.setViewportView(descriptionTextField);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        bedroomText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bedroomText.setText("Bedroom 1/1");

        sleepingNextButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sleepingNextButton.setText(">");
        sleepingNextButton.setEnabled(false);
        sleepingNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepingNextButtonActionPerformed(evt);
            }
        });

        sleepingPrevButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sleepingPrevButton.setText("<");
        sleepingPrevButton.setEnabled(false);
        sleepingPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepingPrevButtonActionPerformed(evt);
            }
        });

        sleepingNewButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sleepingNewButton.setText("New Bedroom");
        sleepingNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepingNewButtonActionPerformed(evt);
            }
        });

        sleepingDeleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sleepingDeleteButton.setText("Delete");
        sleepingDeleteButton.setEnabled(false);
        sleepingDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepingDeleteButtonActionPerformed(evt);
            }
        });

        bed1Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single bed", "Double bed", "Kingsize bed", "Bunk bed" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Bed 1:");

        bed2Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Single bed", "Double bed", "Kingsize bed", "Bunk bed" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Bed 2:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(bedroomText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sleepingNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(sleepingPrevButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sleepingDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bed2Combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bed1Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sleepingNextButton)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedroomText)
                    .addComponent(sleepingNewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bed1Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bed2Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleepingNextButton)
                    .addComponent(sleepingPrevButton)
                    .addComponent(sleepingDeleteButton))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        bedLinenCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bedLinenCheckbox.setText("Bed Linen");
        bedLinenCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedLinenCheckboxActionPerformed(evt);
            }
        });

        towelsCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        towelsCheckbox.setText("Towels");
        towelsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                towelsCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bedLinenCheckbox)
                    .addComponent(towelsCheckbox))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bedLinenCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(towelsCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sleeping");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Bathing");

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        bathroomText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bathroomText.setText("Bathroom 1/1");

        bathingNextButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bathingNextButton.setText(">");
        bathingNextButton.setEnabled(false);
        bathingNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathingNextButtonActionPerformed(evt);
            }
        });

        bathingPrevButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bathingPrevButton.setText("<");
        bathingPrevButton.setEnabled(false);
        bathingPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathingPrevButtonActionPerformed(evt);
            }
        });

        bathingNewButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bathingNewButton.setText("New Bathroom");
        bathingNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathingNewButtonActionPerformed(evt);
            }
        });

        bathingDeleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bathingDeleteButton.setText("Delete");
        bathingDeleteButton.setEnabled(false);
        bathingDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathingDeleteButtonActionPerformed(evt);
            }
        });

        toiletCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toiletCheckbox.setText("Toilet");
        toiletCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toiletCheckboxActionPerformed(evt);
            }
        });

        showerCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showerCheckbox.setText("Shower");
        showerCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showerCheckboxActionPerformed(evt);
            }
        });

        bathCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bathCheckbox.setText("Bath");
        bathCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathCheckboxActionPerformed(evt);
            }
        });

        sharedCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sharedCheckbox.setText("Shared with host");
        sharedCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sharedCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(bathroomText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bathingNewButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(bathingPrevButton)
                        .addGap(10, 10, 10)
                        .addComponent(bathingDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bathingNextButton))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toiletCheckbox)
                            .addComponent(bathCheckbox))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sharedCheckbox)
                            .addComponent(showerCheckbox))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathroomText)
                    .addComponent(bathingNewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toiletCheckbox)
                    .addComponent(showerCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathCheckbox)
                    .addComponent(sharedCheckbox))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathingNextButton)
                    .addComponent(bathingPrevButton)
                    .addComponent(bathingDeleteButton))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        hairDryerCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hairDryerCheckbox.setText("Hair Dryer");
        hairDryerCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairDryerCheckboxActionPerformed(evt);
            }
        });

        shampooCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shampooCheckbox.setText("Shampoo");
        shampooCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shampooCheckboxActionPerformed(evt);
            }
        });

        toiletPaperCheckbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toiletPaperCheckbox.setText("Toilet Paper");
        toiletPaperCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toiletPaperCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hairDryerCheckbox)
                    .addComponent(shampooCheckbox)
                    .addComponent(toiletPaperCheckbox))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hairDryerCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shampooCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toiletPaperCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tvCheckbox.setText("Television");

        wifiCheckbox.setText("Wifi");
        wifiCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wifiCheckboxActionPerformed(evt);
            }
        });

        satelliteCheckbox.setText("Satellite");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Living");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Kitchen");

        basicProvisionsCheckbox.setText("Basic Provisions");

        cookwareCheckbox.setText("Cookware");

        tablewareCheckbox.setText("Tableware");

        dishwasherCheckbox.setText("Dishwasher");
        dishwasherCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishwasherCheckboxActionPerformed(evt);
            }
        });

        ovenCheckbox.setText("Oven");

        stoveCheckbox.setText("Stove");

        microwaveCheckbox.setText("Microwave");

        refrigeratorCheckbox.setText("Refrigerator");

        onRoadParkingCheckbox.setText("On-road Parking");
        onRoadParkingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRoadParkingCheckboxActionPerformed(evt);
            }
        });

        patioCheckbox.setText("Patio");
        patioCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patioCheckboxActionPerformed(evt);
            }
        });

        freeOnSiteParkingCheckbox.setText("Free On-site Parking");

        paidCarParkCheckbox.setText("Paid Car-park");

        streamingCheckbox.setText("Streaming");

        dvdPlayerCheckbox.setText("DVD Player");

        boardGamesCheckbox.setText("Board Games");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Utility");

        centralHeatingCheckbox.setText("Central Heating");
        centralHeatingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centralHeatingCheckboxActionPerformed(evt);
            }
        });

        washingMachineCheckbox.setText("Washing Machine");

        dryingMachineCheckbox.setText("Drying Machine");

        fireExtinguisherCheckbox.setText("Fire Extinguisher");

        firstAidCheckbox.setText("First Aid Kit");

        smokeAlarmCheckbox.setText("Smoke alarm");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Outdoors");

        bbqCheckbox.setText("Barbeque");
        bbqCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbqCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(freeOnSiteParkingCheckbox)
                            .addComponent(onRoadParkingCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paidCarParkCheckbox)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(patioCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bbqCheckbox)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wifiCheckbox)
                                    .addComponent(tvCheckbox)
                                    .addComponent(satelliteCheckbox))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvdPlayerCheckbox)
                                    .addComponent(boardGamesCheckbox)
                                    .addComponent(streamingCheckbox)))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(refrigeratorCheckbox)
                                    .addComponent(microwaveCheckbox)
                                    .addComponent(ovenCheckbox)
                                    .addComponent(stoveCheckbox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dishwasherCheckbox)
                                    .addComponent(tablewareCheckbox)
                                    .addComponent(cookwareCheckbox)
                                    .addComponent(basicProvisionsCheckbox)))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(washingMachineCheckbox)
                            .addComponent(dryingMachineCheckbox)
                            .addComponent(fireExtinguisherCheckbox)
                            .addComponent(smokeAlarmCheckbox)
                            .addComponent(firstAidCheckbox)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(centralHeatingCheckbox, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(refrigeratorCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(microwaveCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ovenCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stoveCheckbox))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(dishwasherCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tablewareCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cookwareCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(basicProvisionsCheckbox)))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(wifiCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tvCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(satelliteCheckbox))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(streamingCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dvdPlayerCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boardGamesCheckbox))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(centralHeatingCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(washingMachineCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dryingMachineCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fireExtinguisherCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smokeAlarmCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstAidCheckbox)))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(freeOnSiteParkingCheckbox)
                            .addComponent(paidCarParkCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onRoadParkingCheckbox)
                            .addComponent(patioCheckbox)
                            .addComponent(bbqCheckbox))))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(addPropertyText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPropertyText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        jFrameInstance.changePanelToDefault();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void propertyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyNameTextFieldActionPerformed

    private void locationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextFieldActionPerformed

    private void streetNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTextFieldActionPerformed

    private void houseNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseNumberTextFieldActionPerformed

    private void placeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeNameTextFieldActionPerformed

    private void postcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postcodeTextFieldActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        updateCurrentBedroomInArray();
        updateCurrentBathroomInArray();
        
        jFrameInstance.changePanelToSpecific(addProperty2Instance);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void bedLinenCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedLinenCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedLinenCheckboxActionPerformed

    private void towelsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_towelsCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_towelsCheckboxActionPerformed

    private void hairDryerCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairDryerCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairDryerCheckboxActionPerformed

    private void shampooCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shampooCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shampooCheckboxActionPerformed

    private void toiletPaperCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toiletPaperCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toiletPaperCheckboxActionPerformed

    private void toiletCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toiletCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toiletCheckboxActionPerformed

    private void showerCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showerCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showerCheckboxActionPerformed

    private void bathCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bathCheckboxActionPerformed

    private void sharedCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sharedCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sharedCheckboxActionPerformed

    private void bathingNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathingNewButtonActionPerformed
        if (currentBathroomPage == 1){
            bathingPrevButton.setEnabled(true);
            bathingDeleteButton.setEnabled(true);
        }
        
        updateCurrentBathroomInArray();
        
        if (currentBathroomPage == bathrooms.size()){
            bathrooms.add(new Bathroom());
        } else {
            bathrooms.add(currentBathroomPage, new Bathroom());
        }
        
        currentBathroomPage++;
        resetBathroomGUIComponents();
        updateBathroomPageInfo();
    }//GEN-LAST:event_bathingNewButtonActionPerformed

    private void dishwasherCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishwasherCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dishwasherCheckboxActionPerformed

    private void onRoadParkingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRoadParkingCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onRoadParkingCheckboxActionPerformed

    private void centralHeatingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centralHeatingCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centralHeatingCheckboxActionPerformed

    private void patioCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patioCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patioCheckboxActionPerformed

    private void wifiCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wifiCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wifiCheckboxActionPerformed

    private void bbqCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbqCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbqCheckboxActionPerformed

    private void sleepingNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepingNextButtonActionPerformed
        if (currentBedroomPage == 1){
            sleepingPrevButton.setEnabled(true);
        }
        
        updateCurrentBedroomInArray();
        currentBedroomPage++;
        updateBedroomGUIComponents();
        updateBedroomPageInfo();
        
        if (currentBedroomPage == bedrooms.size()){
            sleepingNextButton.setEnabled(false);
        }
    }//GEN-LAST:event_sleepingNextButtonActionPerformed

    private void sleepingNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepingNewButtonActionPerformed
        if (currentBedroomPage == 1){
            sleepingPrevButton.setEnabled(true);
            sleepingDeleteButton.setEnabled(true);
        }
        
        updateCurrentBedroomInArray();
        
        if (currentBedroomPage == bedrooms.size()){
            bedrooms.add(new Bedroom());
        } else {
            bedrooms.add(currentBedroomPage, new Bedroom());
        }
        
        currentBedroomPage++;
        resetBedroomGUIComponents();
        updateBedroomPageInfo();
    }//GEN-LAST:event_sleepingNewButtonActionPerformed

    private void sleepingPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepingPrevButtonActionPerformed
        if (currentBedroomPage == bedrooms.size()){
            sleepingNextButton.setEnabled(true);
        }

        updateCurrentBedroomInArray();
        currentBedroomPage--;
        updateBedroomGUIComponents();
        updateBedroomPageInfo();
        
        if (currentBedroomPage == 1){
            sleepingPrevButton.setEnabled(false);
        }
    }//GEN-LAST:event_sleepingPrevButtonActionPerformed

    private void sleepingDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepingDeleteButtonActionPerformed
        if (bedrooms.size() == 2){
            sleepingPrevButton.setEnabled(false);
            sleepingNextButton.setEnabled(false);
            sleepingDeleteButton.setEnabled(false);
        }
        
        bedrooms.remove(currentBedroomPage-1);
        
        if (currentBedroomPage > 1){
            currentBedroomPage--;
        }
        updateBedroomGUIComponents();
        updateBedroomPageInfo();
    }//GEN-LAST:event_sleepingDeleteButtonActionPerformed

    private void bathingPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathingPrevButtonActionPerformed
        if (currentBathroomPage == bathrooms.size()){
            bathingNextButton.setEnabled(true);
        }

        updateCurrentBathroomInArray();
        currentBathroomPage--;
        updateBathroomGUIComponents();
        updateBathroomPageInfo();
        
        if (currentBathroomPage == 1){
            bathingPrevButton.setEnabled(false);
        }
    }//GEN-LAST:event_bathingPrevButtonActionPerformed

    private void bathingNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathingNextButtonActionPerformed
        if (currentBathroomPage == 1){
            bathingPrevButton.setEnabled(true);
        }
        
        updateCurrentBathroomInArray();
        currentBathroomPage++;
        updateBathroomGUIComponents();
        updateBathroomPageInfo();
        
        if (currentBathroomPage == bathrooms.size()){
            bathingNextButton.setEnabled(false);
        }
    }//GEN-LAST:event_bathingNextButtonActionPerformed

    private void bathingDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathingDeleteButtonActionPerformed
        if (bathrooms.size() == 2){
            bathingPrevButton.setEnabled(false);
            bathingNextButton.setEnabled(false);
            bathingDeleteButton.setEnabled(false);
        }
        
        bathrooms.remove(currentBathroomPage-1);
        
        if (currentBathroomPage > 1){
            currentBathroomPage--;
        }
        updateBathroomGUIComponents();
        updateBathroomPageInfo();
    }//GEN-LAST:event_bathingDeleteButtonActionPerformed

    private void updateCurrentBedroomInArray(){
        bedrooms.get(currentBedroomPage-1).setBed1(bed1Combobox.getSelectedItem().toString());
        bedrooms.get(currentBedroomPage-1).setBed2(bed2Combobox.getSelectedItem().toString());
    }
    
    private void updateCurrentBathroomInArray(){
        bathrooms.get(currentBathroomPage-1).toilet = toiletCheckbox.isSelected();
        bathrooms.get(currentBathroomPage-1).bath = bathCheckbox.isSelected();
        bathrooms.get(currentBathroomPage-1).shower = showerCheckbox.isSelected();
        bathrooms.get(currentBathroomPage-1).shared = sharedCheckbox.isSelected();
    }
    
    private void updateBedroomGUIComponents(){
        bed1Combobox.setSelectedItem(bedrooms.get(currentBedroomPage-1).getBed1String());
        bed2Combobox.setSelectedItem(bedrooms.get(currentBedroomPage-1).getBed2String());
    }
    
    private void updateBathroomGUIComponents(){
        toiletCheckbox.setSelected(bathrooms.get(currentBathroomPage-1).toilet);
        bathCheckbox.setSelected(bathrooms.get(currentBathroomPage-1).bath);
        showerCheckbox.setSelected(bathrooms.get(currentBathroomPage-1).shower);
        sharedCheckbox.setSelected(bathrooms.get(currentBathroomPage-1).shared);
    }
    
    private void resetBedroomGUIComponents(){
        bed1Combobox.setSelectedItem("Single bed");
        bed2Combobox.setSelectedItem("None");
    }
    
    private void resetBathroomGUIComponents(){
        toiletCheckbox.setSelected(false);
        bathCheckbox.setSelected(false);
        showerCheckbox.setSelected(false);
        sharedCheckbox.setSelected(false);
    }
    
    private void updateBedroomPageInfo(){
        bedroomText.setText("Bedroom " + currentBedroomPage + "/" + bedrooms.size());
    }
    
    private void updateBathroomPageInfo(){
        bathroomText.setText("Bedroom " + currentBathroomPage + "/" + bathrooms.size());
    }
    
    int saveNewProperty(){
        return 0;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addPropertyText;
    private javax.swing.JCheckBox basicProvisionsCheckbox;
    private javax.swing.JCheckBox bathCheckbox;
    private javax.swing.JButton bathingDeleteButton;
    private javax.swing.JButton bathingNewButton;
    private javax.swing.JButton bathingNextButton;
    private javax.swing.JButton bathingPrevButton;
    private javax.swing.JLabel bathroomText;
    private javax.swing.JCheckBox bbqCheckbox;
    private javax.swing.JComboBox<String> bed1Combobox;
    private javax.swing.JComboBox<String> bed2Combobox;
    private javax.swing.JCheckBox bedLinenCheckbox;
    private javax.swing.JLabel bedroomText;
    private javax.swing.JCheckBox boardGamesCheckbox;
    private javax.swing.JCheckBox centralHeatingCheckbox;
    private javax.swing.JCheckBox cookwareCheckbox;
    private javax.swing.JTextArea descriptionTextField;
    private javax.swing.JCheckBox dishwasherCheckbox;
    private javax.swing.JCheckBox dryingMachineCheckbox;
    private javax.swing.JCheckBox dvdPlayerCheckbox;
    private javax.swing.JCheckBox fireExtinguisherCheckbox;
    private javax.swing.JCheckBox firstAidCheckbox;
    private javax.swing.JCheckBox freeOnSiteParkingCheckbox;
    private javax.swing.JCheckBox hairDryerCheckbox;
    private javax.swing.JTextField houseNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JCheckBox microwaveCheckbox;
    private javax.swing.JButton nextButton;
    private javax.swing.JCheckBox onRoadParkingCheckbox;
    private javax.swing.JCheckBox ovenCheckbox;
    private javax.swing.JCheckBox paidCarParkCheckbox;
    private javax.swing.JCheckBox patioCheckbox;
    private javax.swing.JTextField placeNameTextField;
    private javax.swing.JTextField postcodeTextField;
    private javax.swing.JTextField propertyNameTextField;
    private javax.swing.JCheckBox refrigeratorCheckbox;
    private javax.swing.JButton returnButton;
    private javax.swing.JCheckBox satelliteCheckbox;
    private javax.swing.JCheckBox shampooCheckbox;
    private javax.swing.JCheckBox sharedCheckbox;
    private javax.swing.JCheckBox showerCheckbox;
    private javax.swing.JButton sleepingDeleteButton;
    private javax.swing.JButton sleepingNewButton;
    private javax.swing.JButton sleepingNextButton;
    private javax.swing.JButton sleepingPrevButton;
    private javax.swing.JCheckBox smokeAlarmCheckbox;
    private javax.swing.JCheckBox stoveCheckbox;
    private javax.swing.JCheckBox streamingCheckbox;
    private javax.swing.JTextField streetNameTextField;
    private javax.swing.JCheckBox tablewareCheckbox;
    private javax.swing.JCheckBox toiletCheckbox;
    private javax.swing.JCheckBox toiletPaperCheckbox;
    private javax.swing.JCheckBox towelsCheckbox;
    private javax.swing.JCheckBox tvCheckbox;
    private javax.swing.JCheckBox washingMachineCheckbox;
    private javax.swing.JCheckBox wifiCheckbox;
    // End of variables declaration//GEN-END:variables
}
