/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com2008.team.project;

import java.sql.*;




/**
 *
 * @author 86182
 */
public class Guestsearch extends javax.swing.JPanel {
private Main jFrameInstance;
private String location;
private String location1;
private String location2;
private String location3;
private String startdate;
private String enddate;
private String email;
private Boolean hostView = false;
private PropertyList[] propertyList;
private int currentPage = 1;
private int numberOfPages;
private int propertyId;


    /**
     * Creates new form NewJPanel
     */
    public Guestsearch(Main jFrameInstance, String email,String location) {
        initComponents();
        this.jFrameInstance = jFrameInstance;
        this.locationname.setText(location);
        this.email = email;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        locationname = new javax.swing.JTextField();
        java.text.DateFormat dateFormat1 = new java.text.SimpleDateFormat("dd/MM/yyyy");
        enddatefield =  new javax.swing.JFormattedTextField(dateFormat1);
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        java.text.DateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
        startdatefield =  new javax.swing.JFormattedTextField(dateFormat);
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        prolocation1 = new javax.swing.JTextField();
        prorating1 = new javax.swing.JTextField();
        proname1 = new javax.swing.JTextField();
        prodescription1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        prolocation3 = new javax.swing.JTextField();
        prorating3 = new javax.swing.JTextField();
        proname3 = new javax.swing.JTextField();
        prodescription3 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        prolocation2 = new javax.swing.JTextField();
        prorating2 = new javax.swing.JTextField();
        proname2 = new javax.swing.JTextField();
        prodescription2 = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        prolocation4 = new javax.swing.JTextField();
        prorating4 = new javax.swing.JTextField();
        proname4 = new javax.swing.JTextField();
        prodescription4 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        previousPage = new javax.swing.JButton();
        pageNumber = new javax.swing.JLabel();
        nextPage = new javax.swing.JButton();

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setText("Search");

        setPreferredSize(new java.awt.Dimension(1024, 576));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Switch to Host View");

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setText("Search");

        jButton3.setBackground(new java.awt.Color(255, 204, 153));
        jButton3.setText("Homepage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        locationname.setText("(type the location)");

        try{
            javax.swing.text.MaskFormatter dateMask = new javax.swing.text.MaskFormatter("##/##/####");
            dateMask.install(enddatefield);
        } catch (Exception ex){

        }
        enddatefield.setText(dateFormat1.format(new java.util.Date()));
        enddatefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enddatefieldActionPerformed(evt);
            }
        });

        jButton8.setText("display the start date and end date");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Start date:");

        jLabel2.setText("End date:");

        try{
            javax.swing.text.MaskFormatter dateMask = new javax.swing.text.MaskFormatter("##/##/####");
            dateMask.install(enddatefield);
        } catch (Exception ex){

        }
        startdatefield.setText(dateFormat.format(new java.util.Date()));

        jLabel3.setText("Location:");

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        prolocation1.setText("jTextField1");
        jTabbedPane1.addTab("Location ", prolocation1);

        prorating1.setText("jTextField2");
        jTabbedPane1.addTab("Rating", prorating1);

        proname1.setText("jTextField3");
        jTabbedPane1.addTab("Accomodation name", proname1);

        prodescription1.setText("jTextField4");
        jTabbedPane1.addTab("Description", prodescription1);

        jButton9.setBackground(new java.awt.Color(255, 153, 153));
        jButton9.setText("View more information");

        jLabel4.setText("Recommended accomodations under search:");

        prolocation3.setText("jTextField5");
        jTabbedPane2.addTab("Location ", prolocation3);

        prorating3.setText("jTextField6");
        jTabbedPane2.addTab("Rating", prorating3);

        proname3.setText("jTextField7");
        jTabbedPane2.addTab("Accomodation name", proname3);

        prodescription3.setText("jTextField8");
        jTabbedPane2.addTab("Description", prodescription3);

        jButton10.setBackground(new java.awt.Color(255, 153, 153));
        jButton10.setText("View more information");

        prolocation2.setText("jTextField9");
        jTabbedPane3.addTab("Location", prolocation2);

        prorating2.setText("jTextField10");
        jTabbedPane3.addTab("Rating", prorating2);

        proname2.setText("jTextField11");
        jTabbedPane3.addTab("Accomodation name", proname2);

        prodescription2.setText("jTextField12");
        jTabbedPane3.addTab("Description", prodescription2);

        prolocation4.setText("jTextField13");
        jTabbedPane4.addTab("Location", prolocation4);

        prorating4.setText("jTextField14");
        jTabbedPane4.addTab("Rating", prorating4);

        proname4.setText("jTextField15");
        jTabbedPane4.addTab("Accomodation name", proname4);

        prodescription4.setText("jTextField16");
        jTabbedPane4.addTab("Description", prodescription4);

        jButton11.setBackground(new java.awt.Color(255, 153, 153));
        jButton11.setText("View more information");

        jButton12.setBackground(new java.awt.Color(255, 153, 153));
        jButton12.setText("View more information");

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setText("Past Booking");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 204, 153));
        jButton13.setText("Upcoming Booking");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTextField17.setText("Guest name");

        jLabel5.setText("Guest name:");

        jButton14.setBackground(new java.awt.Color(255, 153, 153));
        jButton14.setText("Book");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 153, 153));
        jButton15.setText("Book");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 153, 153));
        jButton16.setText("Book");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 153, 153));
        jButton17.setText("Book");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        accountButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Icon_Wikipedia_Resized.png"))); // NOI18N
        accountButton.setText("Account");
        accountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        accountButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });

        previousPage.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        previousPage.setText("PREVIOUS");
        previousPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        previousPage.setPreferredSize(new java.awt.Dimension(150, 40));
        previousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPageActionPerformed(evt);
            }
        });

        pageNumber.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pageNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageNumber.setText("[page number]");

        nextPage.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nextPage.setText("NEXT");
        nextPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        nextPage.setPreferredSize(new java.awt.Dimension(150, 40));
        nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accountButton)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(114, 114, 114)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(103, 103, 103)
                                                    .addComponent(locationname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(enddatefield, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(35, 35, 35))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(startdatefield, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8)
                                    .addGap(26, 26, 26))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(246, 246, 246)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(73, 73, 73)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton16))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton15))
                                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton17))
                                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton14)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(pageNumber)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accountButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(startdatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enddatefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9)
                    .addComponent(jButton17)
                    .addComponent(jButton15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16)
                            .addComponent(jButton11)
                            .addComponent(jButton14))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pageNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean search(String location,String startdate,String enddate) {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://stusql.dcs.shef.ac.uk/team024", "team024", "c0857903")) {
                PreparedStatement pstmt = con.prepareStatement("SELECT Information FROM Porperty location=?,startdate=?,enddate=?");
                pstmt.setString(1,location);
                pstmt.setString(2,startdate);
                pstmt.setString(2,enddate);
                ResultSet res1 = pstmt.executeQuery();

                if (res1.next()) {
                    String locationInDB = res1.getString("location");  
                    String startdateInDB = res1.getString("startdate");
                    String enddateInDB = res1.getString("enddate");                   
                    if ((Main.hashString(location).equals(locationInDB))|| (Main.hashString(startdate).equals(startdateInDB))&&(Main.hashString(enddate).equals(enddateInDB)) ){                  
                        return true;
                    }
                    else {                       
                        String errorMessage = "Incorrect details";
                        javax.swing.JOptionPane.showMessageDialog(null, errorMessage, "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        return false;
                    }
                }
                else {
                    
                    String errorMessage = "The accomodation of this location is not found";
                    javax.swing.JOptionPane.showMessageDialog(null, errorMessage, "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                    return false;
                }    
            }

        catch (Exception ex) {
            ex.printStackTrace();
            
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/images/warning_icon_resized.png"));
            String errorMessage = "Connection to database failed. University VPN is required.";
            javax.swing.JOptionPane.showMessageDialog(null, errorMessage, "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE, icon);
        }
        return false;
        
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     Guestmain main = new Guestmain(jFrameInstance);
     jFrameInstance.changePanelToSpecific(main);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fetchPropertyData(String email) {
        
        propertyList = PropertyList.getPropertyList(email);
        
        int n = propertyList.length;
        
        if (n <= 4){
            removePropertyBoxes(4-n);
        } else {
            nextPage.setEnabled(true);
        }
        
        fillPropertyBoxes(0);
        numberOfPages = n == 0 ? 1 : (int)Math.ceil((float)n/3);
        pageNumber.setText("1/" + numberOfPages);

    }
    
    private void removePropertyBoxes(int numBoxesToBeRemoved) {

        if (numBoxesToBeRemoved >= 1){
            prolocation1.setVisible(false);
            prorating1.setVisible(false);
            proname1.setVisible(false);
            prodescription1.setVisible(false);
        }
        if (numBoxesToBeRemoved >= 2){
            prolocation2.setVisible(false);
            prorating2.setVisible(false);
            proname2.setVisible(false);
            prodescription2.setVisible(false);
        }
        if (numBoxesToBeRemoved >= 3){
           prolocation3.setVisible(false);
            prorating3.setVisible(false);
            proname3.setVisible(false);
            prodescription3.setVisible(false);
        }
        if (numBoxesToBeRemoved == 4){
           prolocation4.setVisible(false);
            prorating4.setVisible(false);
            proname4.setVisible(false);
            prodescription4.setVisible(false);
        }
        
    }
    
    
    
    private void fillPropertyBoxes(int numBoxesToBeRemoved) {

        if (numBoxesToBeRemoved >= 1){
           prolocation1.setVisible(false);
            prorating1.setVisible(false);
            proname1.setVisible(false);
            prodescription1.setVisible(false);
        }
        if (numBoxesToBeRemoved >= 2){
            prolocation2.setVisible(false);
            prorating2.setVisible(false);
            proname2.setVisible(false);
            prodescription2.setVisible(false);
        }
        if (numBoxesToBeRemoved >= 3){
           prolocation3.setVisible(false);
            prorating3.setVisible(false);
            proname3.setVisible(false);
            prodescription3.setVisible(false);
        }
        if (numBoxesToBeRemoved == 4){
            prolocation4.setVisible(false);
            prorating4.setVisible(false);
            proname4.setVisible(false);
            prodescription4.setVisible(false);
        }
        
    }
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
     java.util.Date date1;
     java.util.Date date2;
     try{
         date1 = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(startdatefield.getText());
         date2 = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(enddatefield.getText());
         System.out.println(date1 + " " + date2);
     }
     catch (Exception ex){
         
     }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void enddatefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enddatefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enddatefieldActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Guestpastbooking guestpastbooking =new Guestpastbooking(jFrameInstance,location2);
        jFrameInstance.changePanelToSpecific(guestpastbooking);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         Guestupcomingbooking guestupcomingbooking =new Guestupcomingbooking(jFrameInstance,location3);
        jFrameInstance.changePanelToSpecific(guestupcomingbooking);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        location = locationname.getText();
        locationname.setText("");
        startdate = startdatefield.getText();
        startdatefield.setText("");
        enddate = enddatefield.getText();
        enddatefield.setText("");
        
        if (search(location,startdate,enddate)) {
                       
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        //Booking booking1 =new Booking(jFrameInstance);
        //jFrameInstance.changePanelToSpecific(booking1);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        //Booking booking2 =new Booking(jFrameInstance);
        //jFrameInstance.changePanelToSpecific(booking2);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        //Booking booking3 =new Booking(jFrameInstance);
        //jFrameInstance.changePanelToSpecific(booking3);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        //Booking booking4 =new Booking(jFrameInstance);
        //jFrameInstance.changePanelToSpecific(booking4);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        User userPanel = new User(jFrameInstance, email, hostView);
        jFrameInstance.changePanelToSpecific(userPanel);
    }//GEN-LAST:event_accountButtonActionPerformed

    private void previousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPageActionPerformed
        if (currentPage == numberOfPages){
            nextPage.setEnabled(true);
        }
        --currentPage;
        if (currentPage == 1){
            previousPage.setEnabled(false);
        }

        int indexFirstPropOnPage = (currentPage-1)*3;

        pageNumber.setText(currentPage + "/" + numberOfPages);
        fillPropertyBoxes(indexFirstPropOnPage);

    }//GEN-LAST:event_previousPageActionPerformed

    private void nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageActionPerformed
        if (currentPage == 1){
            previousPage.setEnabled(true);
        }
        ++currentPage;
        if (currentPage == numberOfPages){
            nextPage.setEnabled(false);
        }

        int indexFirstPropOnPage = (currentPage-1)*3;

        pageNumber.setText(currentPage + "/" + numberOfPages);
        fillPropertyBoxes(indexFirstPropOnPage);

        if (indexFirstPropOnPage + 3 > propertyList.length){
            removePropertyBoxes(indexFirstPropOnPage - propertyList.length + 3);
        }
    }//GEN-LAST:event_nextPageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JFormattedTextField enddatefield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField locationname;
    private javax.swing.JButton nextPage;
    private javax.swing.JLabel pageNumber;
    private javax.swing.JButton previousPage;
    private javax.swing.JTextField prodescription1;
    private javax.swing.JTextField prodescription2;
    private javax.swing.JTextField prodescription3;
    private javax.swing.JTextField prodescription4;
    private javax.swing.JTextField prolocation1;
    private javax.swing.JTextField prolocation2;
    private javax.swing.JTextField prolocation3;
    private javax.swing.JTextField prolocation4;
    private javax.swing.JTextField proname1;
    private javax.swing.JTextField proname2;
    private javax.swing.JTextField proname3;
    private javax.swing.JTextField proname4;
    private javax.swing.JTextField prorating1;
    private javax.swing.JTextField prorating2;
    private javax.swing.JTextField prorating3;
    private javax.swing.JTextField prorating4;
    private javax.swing.JFormattedTextField startdatefield;
    // End of variables declaration//GEN-END:variables
}
