/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com2008.team.project;

/**
 *
 * @author isabe
 */
public class HostUpcomingBookings extends javax.swing.JPanel {

    /**
     * Creates new form HostUpcomingBookings
     */
    public HostUpcomingBookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPropertyBookingSystem = new javax.swing.JLabel();
        ViewAccount = new javax.swing.JButton();
        Navigation = new javax.swing.JPanel();
        Requests = new javax.swing.JButton();
        PreviousBookings = new javax.swing.JButton();
        UpcomingBookings = new javax.swing.JButton();
        ViewAllProperties = new javax.swing.JButton();

        lblPropertyBookingSystem.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblPropertyBookingSystem.setText("Property Booking System");
        lblPropertyBookingSystem.setPreferredSize(new java.awt.Dimension(370, 40));

        ViewAccount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ViewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Icon_Wikipedia_Resized.png"))); // NOI18N
        ViewAccount.setText("Account");
        ViewAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        ViewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAccount.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAccountActionPerformed(evt);
            }
        });

        Navigation.setBackground(new java.awt.Color(153, 153, 153));
        Navigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        Navigation.setPreferredSize(new java.awt.Dimension(1024, 80));

        Requests.setBackground(new java.awt.Color(153, 153, 153));
        Requests.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Requests.setText("Requests");
        Requests.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        Requests.setPreferredSize(new java.awt.Dimension(237, 50));
        Requests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestsActionPerformed(evt);
            }
        });

        PreviousBookings.setBackground(new java.awt.Color(153, 153, 153));
        PreviousBookings.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PreviousBookings.setText("Previous Bookings");
        PreviousBookings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        PreviousBookings.setPreferredSize(new java.awt.Dimension(237, 50));
        PreviousBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousBookingsActionPerformed(evt);
            }
        });

        UpcomingBookings.setBackground(new java.awt.Color(153, 153, 153));
        UpcomingBookings.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UpcomingBookings.setText("Upcoming Bookings");
        UpcomingBookings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        UpcomingBookings.setPreferredSize(new java.awt.Dimension(237, 50));
        UpcomingBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpcomingBookingsActionPerformed(evt);
            }
        });

        ViewAllProperties.setBackground(new java.awt.Color(153, 153, 153));
        ViewAllProperties.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ViewAllProperties.setText("View All Properties");
        ViewAllProperties.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 5, true));
        ViewAllProperties.setPreferredSize(new java.awt.Dimension(237, 50));
        ViewAllProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllPropertiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationLayout = new javax.swing.GroupLayout(Navigation);
        Navigation.setLayout(NavigationLayout);
        NavigationLayout.setHorizontalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewAllProperties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Requests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(PreviousBookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpcomingBookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NavigationLayout.setVerticalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PreviousBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpcomingBookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Requests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewAllProperties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPropertyBookingSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Navigation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertyBookingSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAccountActionPerformed

    }//GEN-LAST:event_ViewAccountActionPerformed

    private void RequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestsActionPerformed

    private void PreviousBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousBookingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousBookingsActionPerformed

    private void UpcomingBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpcomingBookingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpcomingBookingsActionPerformed

    private void ViewAllPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllPropertiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewAllPropertiesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navigation;
    private javax.swing.JButton PreviousBookings;
    private javax.swing.JButton Requests;
    private javax.swing.JButton UpcomingBookings;
    private javax.swing.JButton ViewAccount;
    private javax.swing.JButton ViewAllProperties;
    private javax.swing.JLabel lblPropertyBookingSystem;
    // End of variables declaration//GEN-END:variables
}
